server:
  port: 8080
  tomcat:
    max-threads: 200
    accept-count: 1000
    min-spare-threads: 100
spring:
  datasource:
    name: miaosha
    url: jdbc:mysql://47.104.159.8:3306/miaosha
    username: root
    password: Star*2018
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml

