server:
  port: 8080
spring:
  datasource:
    name: miaosha
    url: jdbc:mysql://192.168.1.22:3306/miaosha
    username: root
    password: Star*2018
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml

